# Generated by Django 4.2.29 on 2026-03-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('plate', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('fuel', models.CharField(choices=[('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('electric', 'Elétrico'), ('hybrid', 'Híbrido')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-automático')], max_length=20)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatch', 'Hatch'), ('suv', 'SUV'), ('pickup', 'Picape'), ('coupe', 'Cupê'), ('convertible', 'Conversível'), ('wagon', 'Station Wagon'), ('van', 'Van')], max_length=20)),
                ('engine', models.CharField(blank=True, max_length=50)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField()),
                ('doors', models.PositiveSmallIntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('sold', 'Vendido'), ('reserved', 'Reservado'), ('inactive', 'Inativo')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cars/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-created_at'],
            },
        ),
    ]
