# Generated by Django 4.2.29 on 2026-03-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatch', 'Hatch'), ('suv', 'SUV'), ('pickup', 'Picape'), ('coupe', 'Cupê'), ('convertible', 'Conversível'), ('wagon', 'Station Wagon'), ('van', 'Van')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('electric', 'Elétrico'), ('hybrid', 'Híbrido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automático'), ('cvt', 'CVT'), ('semi_automatic', 'Semi-automático')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
