# Generated by Django 4.2.29 on 2026-03-06 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_body_type_alter_car_brand_alter_car_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chevrolet', 'Chevrolet'), ('volkswagen', 'Volkswagen'), ('fiat', 'Fiat'), ('toyota', 'Toyota'), ('hyundai', 'Hyundai'), ('jeep', 'Jeep'), ('renault', 'Renault'), ('ford', 'Ford'), ('nissan', 'Nissan'), ('honda', 'Honda'), ('peugeot', 'Peugeot'), ('kia', 'Kia'), ('mitsubishi', 'Mitsubishi'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('audi', 'Audi'), ('citroen', 'Citroën'), ('caoa_chery', 'CAOA Chery'), ('byd', 'BYD'), ('volvo', 'Volvo'), ('land_rover', 'Land Rover'), ('porsche', 'Porsche'), ('subaru', 'Subaru'), ('suzuki', 'Suzuki'), ('dodge', 'Dodge'), ('ram', 'RAM'), ('lexus', 'Lexus'), ('mini', 'MINI'), ('jaguar', 'Jaguar'), ('mazda', 'Mazda'), ('haval', 'Haval'), ('gac', 'GAC Motor'), ('great_wall', 'Great Wall'), ('mg', 'MG'), ('geely', 'Geely'), ('effa', 'Effa'), ('jac', 'JAC Motors'), ('lifan', 'Lifan'), ('shineray', 'Shineray'), ('foton', 'Foton'), ('iveco', 'Iveco'), ('alfa_romeo', 'Alfa Romeo'), ('fiat_professional', 'Fiat Professional'), ('mercedes_van', 'Mercedes-Benz Vans'), ('polestar', 'Polestar'), ('tesla', 'Tesla'), ('genesis', 'Genesis'), ('infiniti', 'Infiniti'), ('acura', 'Acura'), ('outros', 'Outros')], max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.brand'),
        ),
    ]
